### PR TITLE
chore(ci) enable travis ci

### PR DESCRIPTION
**Pull request by gszr**

### CODE REVIEW

**Comment by Tieske** [comment]
@gszr I think you need to encode the secrets in the proper way, instructions are different for open-source and closed repo's. See the pinned item in the "fast-track-alerts" channel.

**Review by dndx — APPROVED** [review]

**Comment by Tieske** [comment]
@gszr You added a config file `.luacheckrc`, I think you should removed it again, and then run `pongo init` from the repo. It will add all the standard config files, based on Kong standards. This includes more (and better) files.

**Comment by Tieske** [comment]
I justed update it, so please pull latest master of Pongo first

**Comment by gszr** [comment]
> I justed update it, so please pull latest master of Pongo first

Done, thanks @Tieske!

**Pull request merged**
